News post about project state
konstructs/konstructs.github.io pull request #21
Opened 2017-07-26 16:48 UTC by nsg

This is a draft post with various project update, what do you think?

2017-07-26 22:51 UTC, petterarvidsson requested changes
Please fix the typos, but otherwise this is a great update :+1:

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +When it comes to the server the thing we need to improve is easy of use, it's a little hard to understand hot to get started with a new plugin, and it can be a little tricky as a server administrator
hot -> how

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +* Make distributions, the core server is just plain boring. It's a platform for plugins, and they are what makes the game fun to playr. We plan to release a pre-packaged official distribution of the
playr -> play

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +We played with the idea to rewrite the client in something else, like Go or Rust but decided that C++ ecosystem and all the available integrations are worth a little plain. We also looked what option
plain -> pain

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +* Block inventory management will be improved, we plan to make a system that standardizes a default input and output inventory to blocks that support it. This allows other blocks to pick up or place
"or place items." -> " or place items from or into other blocks."

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +With the above done we plan to focus on gaming experience and fun, this work will mainly be focused around plugins, the official distribution and play.konstructs.org with is the official server.
with -> which

2017-07-26 22:51 UTC, petterarvidsson commented on _posts/2017-07-26-short-term-plans.md
> +What direction is the project heading you may wonder? Our overall [roadmap](/documentation/roadmap/) is still true but how do we plan to get there from this point? Lets discuss that by citing the roa
"You may wonder in which direction the project is heading?"

"but" -> ", but"

2017-07-26 23:24 UTC, nsg commented
still a draft ... so I will probably rewrite it some more. So, not to long post then?

2017-07-27 08:13 UTC, petterarvidsson commented
I like that it is a longer one, there a re lots of things to write about.

2017-07-28 18:15 UTC, merged